### ISSUE TITLE
Issue with Git LFS

### ISSUE THREAD

**Issue by SMUEric1127** [SouthernMethodistUniversity/hpc_docs#155]
Hi all,

I'm just wonder how can I install Git LFS without sudo permissions? I also see that the documents doesn't mention a lot about install some packages,

Thank you!

**Comment by jrlagrone** [comment]
Git-lfs is installed on M3. It can be loaded with, for example,

```
module load gcc/11.2.0
module load git-lfs/3.1.2-5c2wtrg
```

On the SuperPod

```
module load gcc/11.2.0
module load git-lfs/3.3.0-celzncr
```
